version: "1"
services:

  shop:
    image: spring-shop:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    expose:
      - 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./src/main/resources/root:/src/main/resources/root
      - ./src/main/resources/templates:src/main/resources/templates

  postgres_db:
    image: postgres:11.8
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data